params2plot:
  - cosmological_parameters--omega_m
  - cosmological_parameters--s8
  - cosmological_parameters--sigma_8
  - cosmological_parameters--w
  - cosmological_parameters--wa
  # - cosmological_parameters--wp
  # - cosmological_parameters--h0
  # - cosmological_parameters--omega_b
  # - cosmological_parameters--n_s
  # - cosmological_parameters--a_s
  # - cosmological_parameters--neff
  # - cosmological_parameters--meffsterile
  # - shear_calibration_parameters--m1
  # - shear_calibration_parameters--m2
  # - shear_calibration_parameters--m3
  # - shear_calibration_parameters--m4
  # - lens_photoz_errors--bias_1
  # - lens_photoz_errors--bias_2
  # - lens_photoz_errors--bias_3
  # - lens_photoz_errors--bias_4
  # - lens_photoz_errors--bias_5
  # - bias_lens--b1
  # - bias_lens--b2
  # - bias_lens--b3
  # - bias_lens--b4
  # - bias_lens--b5
  # - intrinsic_alignment_parameters--a1
  # - intrinsic_alignment_parameters--a2
  # - intrinsic_alignment_parameters--alpha1
  # - intrinsic_alignment_parameters--alpha2
  # - intrinsic_alignment_parameters--bias_ta
  # - cosmological_parameters--omega_k
  # - npg_parameters--a2
  # - npg_parameters--a3
  # - npg_parameters--a4
  # - modified_gravity--sigma0
  # - modified_gravity--mu0

# Truth values of various parameters
truth:
  cosmological_parameters--omega_m: 0.31
  COSMOLOGICAL_PARAMETERS--SIGMA_8: 0.7585308986782913
  cosmological_parameters--s8:      0.77106944892
  cosmological_parameters--omega_b: 0.051
  cosmological_parameters--h0:      0.69
  cosmological_parameters--n_s:     0.965
  cosmological_parameters--w:       -1.0
  cosmological_parameters--wa:       0.0

# param1, param2, n-sigma contour
pairs_plot_2d:
  - ['cosmological_parameters--omega_m', 'cosmological_parameters--s8', 0.3]
  - ['cosmological_parameters--w', 'cosmological_parameters--wa', 0.3]
